### ISSUE TITLE
Missing PIM/calendar/todo icons

### ISSUE THREAD

**Issue by silverhook** [EliverLara/candy-icons#2]
Instead of opening a huge amount of issues, I will group here what I’m missing from the whole set of PIM:

- [x] KOrganizer
- [x] Zanshin
- [x] generic calendar app
- [x] generic ToDo app
- [ ] action icons for these – but, to be honest, the default Breeze action icons work very well with the set (at least on dark themes) already.

**Comment by silverhook** [comment]
Awesome to see progress here! Thanks :smiley_cat:

If I see correctly in master, the KOrganizer icon seems more like a todo list than a calendar. While KOrganizer can handle both, its primary use is calendar, so it might make sense to use the calendar icon instead.

I forgot to mention that Zanshin is a ToDo app, so at least as a temporary solution linking it to point to the generic ToDo app would already help :)
